apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  000-default.conf: |-
    <VirtualHost *:80>
        ServerAdmin admin@example.com
        ServerName localhost
        DocumentRoot /var/www/localhost
        <Directory /var/www/localhost/mediawiki>
            DirectoryIndex index.html index.html.var index.php
            Options Indexes FollowSymLinks
            AllowOverride None
            Require all granted
        </Directory>

        # Send apache logs to stdout and stderr
        CustomLog /proc/self/fd/1 common
        ErrorLog /proc/self/fd/2
    </VirtualHost>
